### PR TITLE
Add MODULE_VERSION(IT87_DRIVER_VERSION) back to it87.c

### PR DESCRIPTION
**Pull request by konomikitten**
MODULE_VERSION(IT87_DRIVER_VERSION) somehow ended up missing in it87.c. This causes DKMS v3.0.10 module version sanity check to fail as the module lacks a version.

### CODE REVIEW

**Comment by frankcrawford** [comment]
@konomikitten  I don't know if this will ever be merged in as nothing has been done with this repo for years.

If you want to work on what is likely to be the latest version, I recommend you look on my fork,  https://github.com/frankcrawford/it87

**Comment by konomikitten** [comment]
> @konomikitten I don't know if this will ever be merged in as nothing has been done with this repo for years.
> 
> If you want to work on what is likely to be the latest version, I recommend you look on my fork, https://github.com/frankcrawford/it87

Your repo lacks a debian build directory which makes it less appealing to me and I don't feel super confident about adding one too it. Hence why I've focused on this repo instead.

**Comment by frankcrawford** [comment]
True, but that is easily fixed.  While I don't use debian, if you want to do a PR to add it, feel free.  You could even just copy the one from here then push it.  I would expect you to test it, but the basis of the repo and the driver are the same, so it should be fairly easy.

It is just I don't think any changes here will ever be merged.

**Comment by konomikitten** [comment]
I'll look into it, would be nice to have.

**Comment by hannesha** [comment]
Hello, I would recommend some of the newer forks too.
Thanks @frankcrawford for continuing development on the driver.

**Comment by hannesha** [comment]
I'm going to close this request and archive the repository, as this is no longer maintained on my side.

**Pull request closed without merging**
